### ISSUE TITLE
Impossible de lancer le demon avec un mot de passe trop complexe

### ISSUE THREAD

**Issue by Banzzouille** [Jeremie-C/plugin-MerossIOT#1]
Bonjour,
j'ai essayé ce matin de configurer votre plugin dans ma box domotique Jeedom.
Aucun soucis pour l'installer, ni les dépendances.
Par contre, pas moyen de lancer le démon.
J'ai donc vérifie 10 fois que mon de passe était correct car j'avais toujours cette erreur : "meross_iot.api.UnauthorizedException".
Pour info, impossible que je me sois trompé de mot de passe, j'utilise un gestionnaire (bitwarden) et j'ai juste a faire un copier-coller.
Dans le doute, j'ai changé mon mot de passe en enlevant les caractères # et $ et la , paf, ça marche.

Si vous pouviez vérifier que c'est bien ça le soucis, faire une modif ou alors une indication que les mot de passe avec caractères spéciaux ne fonctionne pas ?

Merci

**Comment by gregleg** [comment]
j'ai le meme souci le demon ne se lance pas

**Comment by Banzzouille** [comment]
Moi j'ai juste changé mon mot de passe dans l'appli mobile Meross en m'etant un mdp plus simple. Je l'ai ressaisi a nouveau dans le plugin et la pas de soucis, une fois les dependance correctement installées, le démon s'est lancé.

**Comment by gregleg** [comment]
Mon mot de passe c 7 lettre minuscule  un chiffre

**Comment by gregleg** [comment]
Même en changement de mot de passe 7 lettre cela est pareil

**Comment by Banzzouille** [comment]
Moi jetais bien sur que c’était le même.  Si c'est votre cas, il ne reste plus qu'a attendre le retour du dev....
Je ne pourrais pas plus vous aider

**Comment by Jeremie-C** [comment]
Bonjour.
Signalement validé pour les caractères spéciaux.
Je fait des tests pour savoir si ça vient de mon code ou de la librairie utilisée comme dépendance.
Je reviens vers vous très vite.

**Comment by gregleg** [comment]
D’accord merci car je suis avec le plugin de nextdom cela fonctionne  mais je voulais tester le votre

**Comment by Banzzouille** [comment]
Ce n'est pas le miens!! 
Je n'ai rien a voir avec ce repo :)

**Comment by Jeremie-C** [comment]
Bonjour,
Bug corrigé dans mon code.
Mise à jour dispo dès maintenant sur le GIT et sous quelques heures dans jeedom.
Merci pour cette remontée.

**Comment by bsdev90** [comment]
Bonjour,
Plugin téléchargé via le market Jeedom aujourd'hui, problème toujours présent. En enlevant les caractères spéciaux de mon mot de passe ça fonctionne.

**Comment by Jeremie-C** [comment]
Bonjour,
merci de donner le / les caractères spéciaux car pour moi impossible de reproduire le problème.
Merci.
