### ISSUE TITLE
Cycle mise à jour puissance

### ISSUE THREAD

**Issue by Krankhore** [Jeremie-C/plugin-MerossIOT#2]
Le cycle de mise à jour des puissances n'est pas pris en compte et la durée est forcée à 30 secondes.
Dans MerossIOT.class.php ligne 654 ,    _$updp = config::byKey('MerossUPD', 'MerossIOT');_
La valeur retournée est de type string et donc on bascule dans la valeur par défaut
       _**if( is_int($updp) ) {**
            if( $updp < 5 ) {
                $updp = 30;
                log::add('MerossIOT','info',__('Cycle mise à jour puissance inférieur à 5 secondes.', __FILE__));
            }
        } else {
            **$updp = 30;**
        }_

Pour que cela fonctionne, j'ai ajouté un intval()  : _$updp = intval(config::byKey('MerossUPD', 'MerossIOT'));_

J'utilise le plugin sous Nextdom 0.6.8 et sur une Debian stretch.

Et merci pour ce super plugin.

**Comment by Jeremie-C** [comment]
Bonsoir.
Bug confirmé.
Correction dans la prochaine mise a jour.
Merci pour le signalement.

**Comment by Krankhore** [comment]
J'ai vérifié que le même souci existe sous Jeedom 3.3.39 et Debian stretch
