### ISSUE TITLE
Paramètres des équipements remis à leur valeur par défaut

### ISSUE THREAD

**Issue by Krankhore** [Jeremie-C/plugin-MerossIOT#4]
J'ai saisie des valeurs max sur la commande puissance et courant de certains de mes équipements MSS310  car la consommation est loin des 4000 W et 17A mis par défaut.
C'est prévu et ça marche sans problème , par contre les valeurs par défaut sont remises systématiquement.
C'est à priori remis en place lorsque j’exécute la commande refresh de l'équipement en question.
Je me me sers tous les jours de cette commande refresh par scénario à 23h59 pour être certain de récupérer la dernière valeur de consommation du jour et la stocker.

Est ce voulu que cela écrase les paramètres de l’équipement ou est ce un bug ?
Et est ce que le refresh est bien un moyen de forcer la mise à jour des valeurs de l'équipement  ( puissance, courant, tension et consommation) ?

**Comment by Jeremie-C** [comment]
Bonjour.
Bug confirmé.
Correction dans la prochaine mise a jour.
Merci pour le signalement.

**Comment by Jeremie-C** [comment]
Bonjour,

Le refresh recréer les commandes manquantes (ou nouvelles commandes) et de fait il récupère aussi les valeurs.

Normalement, il n'y as pas besoin de faire un refresh pour récupérer les valeurs.
Tension / Courant / Puissance : toutes les x secondes suivant votre paramètrage.
Consommation : via le cron du plugin toutes les 10 minutes.

Bonne journée.

**Comment by Jeremie-C** [comment]
Bonjour,
Bug corrigé dans mon code.
Mise à jour dispo dès maintenant sur le GIT et sous quelques heures dans jeedom.
Merci pour cette remontée.

**Comment by Krankhore** [comment]
J'ai installé la version, c'est bon pour moi.
Merci beaucoup pour ce plugin.
