### ISSUE TITLE
Le nom de l'équipement ne peut pas être vide

### ISSUE THREAD

**Issue by admfj** [Jeremie-C/plugin-MerossIOT#8]
Bonjour,

Le plugin fonctionne quelques heures et puis donne cette erreur ci. J'ai une vingtaine d'appareils Meross et le problème se pose sur plusieurs appareils tout d'un coup.

J'ai la dernière version installée du plugin (2020-04-29 01:06:40) et de Jeedom (4.0.54).

Pour solutionner le soucis, je dois arrêter le Demon et le relancer (synchroniser ne suffit pas à résoudre le problème). Mais, parfois, cela ne suffit pas à résoudre le problème.

Pensez-vous que vous pourriez regarder au problème ? Car cela m’ennuie beaucoup : je ne sais en effet faire aucun scénario à cause de ce soucis. Merci et bonne journée.

Exception happened during processing of request from
Traceback (most recent call last):
File « /usr/lib/python3.7/socketserver.py », line 316, in _handle_request_noblock
self.process_request(request, client_address)
File « /usr/lib/python3.7/socketserver.py », line 347, in process_request
self.finish_request(request, client_address)
File « /usr/lib/python3.7/socketserver.py », line 360, in finish_request
self.RequestHandlerClass(request, client_address, self)
File « /usr/lib/python3.7/socketserver.py », line 720, in init
self.handle()
File « /var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py », line 104, in handle
response[‹ result ›] = response’result’
File « /var/www/html/plugins/MerossIOT/resources/MerossIOTd/MerossIOTd.py », line 296, in syncMerossConso
if device.online and device.supports_consumption_reading():
File « /usr/local/lib/python3.7/dist-packages/meross_iot/cloud/device.py », line 162, in supports_consumption_reading
return CONSUMPTIONX in self.get_abilities()
File « /usr/local/lib/python3.7/dist-packages/meross_iot/cloud/device.py », line 134, in get_abilities
self._abilities = self.execute_command(« GET », ABILITY, {})[‹ ability ›]
File « /usr/local/lib/python3.7/dist-packages/meross_iot/cloud/device.py », line 126, in execute_command
return self.__cloud_client.execute_cmd(self.uuid, command, namespace, payload, callback=callback, timeout=timeout)
[2020-05-08 06:54:39][ERROR] : Erreur exécution de la commande [Salon][Salon Parafoudre 1][Refresh] : Le nom de l’équipement ne peut pas être vide : MerossIOT Object ( [id:protected] => [name:protected] => [logicalId:protected] => [generic_type:protected] => [object_id:protected] => [eqType_name:protected] => MerossIOT [eqReal_id:protected] => [isVisible:protected] => 0 [isEnable:protected] => 0 [configuration:protected] => Array ( [online] => 0 ) [timeout:protected] => 0 [category:protected] => [display:protected] => [order:protected] => 9999 [comment:protected] => [tags:protected] => [_debug:protected] => [_object:protected] => [_needRefreshWidget:protected] => [_timeoutUpdated:protected] => [_batteryUpdated:protected] => [_changed:protected] => 1 )

D'avance merci.

**Comment by Jeremie-C** [comment]
Bonjour.
Effectivement, la dernière mise a jour a introduit un bug sur cette fonction.
Je lance les recherches et vous tient au courant rapidement.
Merci.

**Comment by Jeremie-C** [comment]
Bonsoir,

Je viens de mettre en ligne une nouvelle version qui corrige le problème.

Bonne soirée.

**Comment by admfj** [comment]
Merci beaucoup à vous Jeremie-C.
