### ISSUE TITLE
Import Error, no modules names typing

### ISSUE THREAD

**Issue by xcouvy** [Jeremie-C/plugin-MerossIOT#9]
Hello, since I installed this extension on my RPI 3+ Jeedom system, I can't launch the demon.
Please find in this link the logs files :
https://1drv.ms/u/s!Asa2K8vvEiBWk4xDbpJRnoOK_ifdsA?e=taJ83z
Many thanks !!!

**Comment by Jeremie-C** [comment]
Hello,
Your python version is 3.4 but my plugin need 3.5.
Please update your python version.
Thanks

**Comment by xcouvy** [comment]
Hollo, thanks I will try that !
